# Generated by Django 3.2.12 on 2022-09-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='game',
        ),
    ]
